import numpy as np
import matplotlib.pyplot as plt
p = np.loadtxt('pressure.csv',delimiter=',')
u = np.loadtxt('u_velocity.csv',delimiter=',')
v = np.loadtxt('v_velocity.csv',delimiter=',')
xnodes = np.loadtxt('xnodes.csv',delimiter=',')
ynodes = np.loadtxt('ynodes.csv',delimiter=',')
#generate contour plot
plt.figure()
plt.contour(xnodes,ynodes,u)
plt.pcolormesh(xnodes,ynodes,v,cmap = plt.get_cmap('rainbow'))
plt.colorbar()
plt.xlabel('x[m]')
plt.ylabel('y[m]')
plt.title('Horizontal Velocity Around a Car')
xcar = np.loadtxt('x_car.csv',delimiter=',')
ycar = np.loadtxt('y_car.csv',delimiter=',')
plt.scatter(xcar,ycar)
plt.axes().set_aspect(1)
plt.savefig('u_velocity.png')
#Generate a new figure
plt.figure()
plt.contour(xnodes,ynodes,p)
plt.pcolormesh(xnodes,ynodes,v,cmap = plt.get_cmap('rainbow'))
plt.streamplot(xnodes,ynodes,u,v,density=1.5)
plt.scatter(xcar,ycar)
plt.xlabel('x[m]')
plt.ylabel('y[m]')
plt.title('Streamlines Around a Car')
plt.axes().set_aspect(1)
plt.savefig('u_velocity.png')
